name: my_web_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  uuid: ^4.4.0

  cupertino_icons: ^1.0.8

  # Supabase Flutter SDK für CRUD über Supabase
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
