name: Preview to Firebase Hosting on PR
on:
  pull_request:
    branches: [main]
concurrency:
  group: hosting-previews
  cancel-in-progress: true
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter config --enable-web
      - run: flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: flutter-test-c2aca
          channelId: pr-${{ github.event.number }}
          entryPoint: .
          expires: 14d
